### ISSUE TITLE
Issues with chromosome splitting and shift estimation

### ISSUE THREAD

**Issue by RicciAle** [uio-bmi/graph_peak_caller#5]
Good morning,
I'm trying to use split_vg_json_reads_into_chromosomes on the file created with the following code: 

`vg filter -r 0.95 -s 2.0 -q 60 -fu mapped.gam > filtered.gam`

It comes from the mapping of the raw reads of the isogenic replicate 1 in ENCSR000DUB of ENCODE to the human genome graphs you've put the link to, and it seems like the command reaches roughly chromosome 7 instead of splitting into all the chromosomes.

Moreover, if i try to use estimate_shift in order to have the fragment length, which is necessary for the peak calling, I get this error:

`2019-04-27 09:53:17,472, DEBUG: Interval Intv((1173002:9), (1173006:3), [1173002, 1173003, 1173005, 1173006], Graph, lc=86) is not valid interval in graph`
`2019-04-27 09:53:17,473, ERROR: Found an alignment not compatible with the graph that was used. Are you sure alignments/intervals are mapped to the same graph that was used? Turn on debuging with --verbose 2 to see full log.`

What shall I do in order to fix this right?
Thank you in advance and please tell me if I didn't make myself clear!

**Comment by ivargr** [comment]
Hi!

Thanks for reaching out!

My guess is that something goes wrong when splitting the reads. I assume you converted `filtered.gam` to json using `vg view -aj` before splitting the file? Would you be able to share either the json file or the `filtered.gam` file with me, and I can have a look at it and see if I can find out what is going wrong :)

**Comment by RicciAle** [comment]
Yes, I converted the .gam file using vg view -aj!
How shall I send you the .gam or the .json file, since they have size respectively of 510 MB and 4 GB?

**Comment by RicciAle** [comment]
No worries, I solved the problem with just unzipping the human genome folder you sent me the link about and restarting the analysis!

**Comment by ivargr** [comment]
Great, glad to hear :)
